
const FilterSorterActionTypes = {
    TOGGLE_FILTER_SORTER_HIDDEN: 'TOGGLE_FILTER_SORTER_HIDDEN',
    CHANGE_FILTER_SORTER: 'CHANGE_FILTER_SORTER',
    CLEAR_FILTER_SORTER: 'CLEAR_FILTER_SORTER',
    FETCH_FILTER_SORTER_MAP: 'FETCH_FILTER_SORTER_MAP',
};

export default FilterSorterActionTypes;